# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Using lychee instead
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - SPELL_CSPELL

# Remove: To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
EMAIL_REPORTER: false

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true

FILTER_REGEX_EXCLUDE: CHANGELOG.md

FORMATTERS_DISABLE_ERRORS: false

HTML_HTMLHINT_FILTER_REGEX_EXCLUDE: ^index.html

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# Remove initial MegaLinter graphic
PRINT_ALPACA: false

# Disable creating report directory
REPORT_OUTPUT_FOLDER: none

RUBY_RUBOCOP_FILTER_REGEX_EXCLUDE: ^_plugins

YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (^_data/|^_config.yml)

YAML_V8R_FILTER_REGEX_EXCLUDE: (^_data/|^_config.yml)

VALIDATE_ALL_CODEBASE: true
