# https://lychee.cli.rs/#/usage/config

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs
cache = true

# Discard all cached requests older than this duration
max_cache_age = "1d"

#############################  Runtime  #############################

# Maximum number of concurrent link checks
max_concurrency = 128

#############################  Requests  ############################

# Comma-separated list of accepted status codes for valid links.
accept = [999]

#############################  Exclusions  ##########################

# Exclude URLs and mail addresses from checking (supports regex)
# https://github.com/cotes2020/jekyll-theme-chirpy/issues/758
exclude = [
  "https://fonts.(googleapis|gstatic).com/",
  "https://ruzickap.github.io/projects/",
  # Due to: [TIMEOUT] https://twitter.com/Ruzicka_Petr | Timeout
  "https://twitter.com/Ruzicka_Petr",
  "https://*k01.k8s.mylabs.dev/*",
]

# Exclude these filesystem paths from getting checked
exclude_path = [
  "_tabs/projects.md",
  # ignore due to https://github.com/lycheeverse/lychee/issues/259
  "./public/",
  "./vendor/",
  "./_site/",
]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true
exclude_all_private = false

# Exclude all mail addresses from checking
exclude_mail = true
