# https://lychee.cli.rs/#/usage/config

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs
cache = true

# Discard all cached requests older than this duration
max_cache_age = "1d"

#############################  Runtime  #############################

# Maximum number of concurrent link checks
max_concurrency = 128

#############################  Requests  ############################

# Comma-separated list of accepted status codes for valid links.
accept = [999]

#############################  Exclusions  ##########################

# Exclude URLs and mail addresses from checking (supports regex)
exclude = [
  # keep-sorted start
  # Ignore all URLs with '{ ... }' - BASH / Ansible variable in URL
  '%7B.*%7D',
  # Ignore all URLs with '$' - BASH variable in URL
  '\$',
  'analytics\.eu\.umami\.is/',
  'cdn\.com',
  # Ignore all URLs which starts with 'file://'
  'file://',
  'fonts\.(googleapis|gstatic)\.com',
  'mylabs\.dev',
  'stackexchange\.com',
  'stackoverflow\.com',
  'username\.github\.io',
  'www\.facebook\.com/sharer/sharer\.php\?title=TITLE&u=URL',
  'www\.googletagmanager\.com',
  'www\.threads\.net/intent/post',
  # keep-sorted end
]

# Exclude these filesystem paths from getting checked
exclude_path = [
  "CHANGELOG.md",
  "_tabs/projects.md",
]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true
exclude_all_private = true
