# Comma-separated list of accepted status codes for valid links
accept = [ 999 ]

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs
cache = true

# Exclude all private IPs from checking
exclude-all-private = true

# Exclude all mail addresses from checking
exclude_mail = true

# Exclude URLs and mail addresses from checking (supports regex)
# https://github.com/cotes2020/jekyll-theme-chirpy/issues/758
exclude = [
  "https://fonts.(googleapis|gstatic).com/",
  "https://blog.ruzicka.dev/projects/",
]

# Exclude these filesystem paths from getting checked
exclude_path = [
  "_tabs/projects.md",
  "public/projects/index.html",
  "./_tabs/",
  "./vendor/",
  "./_site/",
]

# Discard all cached requests older than this duration
max-cache-age = "1d"

# Don't show interactive progress bar while checking links
no-progress = true
